# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: My First Workflow

on: push

jobs:
    my-first-job:
        runs-on:  ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6

            - name: welcome message
              run: echo "My first git hub action job execution"
                   ls -ltra 
                   cat README.md
            - name: Generate ASCII artwork
              run: cowsay -f dragon "I am a dragon" >> dragon.txt

            # - name: List files
            #   run: ls -ltr

            # - name: Read file
            #   run: cat README.md
