# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Generate ASCII Artwork

on:
  push

jobs:
  ascii_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List the files
        run:  ls -ltra

      - name: Exececuting the Cowsay Program
        run: ./ascii-script.sh

